name: ROS2 CI

permissions: write-all

on:
  pull_request:
    branches:
      - 'ros2/*'
      - 'ros2'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - humble
          - rolling
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
            ros_distribution: foxy
            ros_version: 2
          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
            ros_distribution: galactic
            ros_version: 2
          # Humble Hawksbill  (May 2022 - 2027
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2    
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: install deps
        run: |
          sudo apt update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
          python3-pip telnet iptables iproute2
      - uses: actions/checkout@v3
      - name: build and test
        id: build_and_test_step
        # Use antmicro's Renode linux distro that supports
        # vivid (virtual device emulating a v4l2 device)
        # https://github.com/antmicro/renode-linux-runner-action
        uses: flynneva/renode-linux-runner-action@main
        with:
          shared-dir: ./
          image: https://github.com/antmicro/renode-linux-runner-action/releases/download/v0/images.tar.xz
          renode-run: |
            ls /dev | grep video
            source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
            ls
            colcon build
            colcon test
          devices: vivid
